get:
  tags:
    - Tools
  summary: get tenant configuration
  operationId: GetConfig
  consumes: []
  produces:
    - text/plain
    - application/json
    - text/json
  parameters:
    - name: tenantId
      in: query
      description: ''
      required: false
      type: string
  responses:
    '200':
      description: Success
      schema:
        $ref: '#/definitions/AuthorizationTenantConfiguration'
    '400':
      description: Bad Request
      schema:
        $ref: '#/definitions/ProblemDetails'
    '401':
      description: Unauthorized
      schema:
        $ref: '#/definitions/ProblemDetails'
