post:
  tags:
    - Tools
  summary: set tenant configuration
  operationId: SetConfig
  consumes:
    - application/json-patch+json
    - application/json
    - text/json
    - application/*+json
  produces:
    - text/plain
    - application/json
    - text/json
  parameters:
    - name: tenantId
      in: query
      description: ''
      required: false
      type: string
    - name: authorizationTenantConfiguration
      in: body
      description: ''
      required: false
      schema:
        $ref: '#/definitions/AuthorizationTenantConfiguration'
  responses:
    '200':
      description: Success
      schema:
        $ref: '#/definitions/AuthorizationTenantConfiguration'
    '400':
      description: Bad Request
      schema:
        $ref: '#/definitions/ProblemDetails'
    '401':
      description: Unauthorized
      schema:
        $ref: '#/definitions/ProblemDetails'
