openapi: 3.0.0
info:
  version: 1.0.154.9
  title: Plexure Authorization Service
  description: Provides means for consumers api and SDK to get authorization.
  contact:
    name: Plexure Support
    url: 'https://support.plexure.com'
    email: support@plexure.com
paths:
  /Authentication/ConsumerAuthentication:
    $ref: paths\Authentication@ConsumerAuthentication.yaml
  /Authentication/ValidateOtp:
    $ref: paths\Authentication@ValidateOtp.yaml
  /Authorization/ServiceTokens:
    $ref: paths\Authorization@ServiceTokens.yaml
  /Authorization/ConsumerTokens:
    $ref: paths\Authorization@ConsumerTokens.yaml
  /Authorization/ConsumerMfaTokens:
    $ref: paths\Authorization@ConsumerMfaTokens.yaml
  /Authorization/DeviceTokens:
    $ref: paths\Authorization@DeviceTokens.yaml
  /Authorization/MerchantTokens:
    $ref: paths\Authorization@MerchantTokens.yaml
  /Authorization/ActivityTokens:
    $ref: paths\Authorization@ActivityTokens.yaml
  /Authorization/ActivityTokens/external:
    $ref: paths\Authorization@ActivityTokens@external.yaml
  /Authorization/ActivityTokens/internal:
    $ref: paths\Authorization@ActivityTokens@internal.yaml
  /Authorization/AccessToken:
    $ref: paths\Authorization@AccessToken.yaml
  /Tools/ValidateAccessTokens:
    $ref: paths\Tools@ValidateAccessTokens.yaml
  /Tools/GetTenantConfig:
    $ref: paths\Tools@GetTenantConfig.yaml
  /Tools/SetTenantConfig:
    $ref: paths\Tools@SetTenantConfig.yaml
definitions:
  ConsumerAuthentication:
    type: object
    properties:
      partitionKey:
        type: string
        readOnly: true
      id:
        format: uuid
        type: string
      deactivatedDate:
        format: date-time
        type: string
      mfaDetails:
        $ref: '#/definitions/ConsumerAuthenticationMfaDetails'
      status:
        type: string
  ConsumerAuthenticationMfaDetails:
    type: object
    properties:
      channel:
        enum:
          - email
        type: string
      identifier:
        type: string
      unusedOTPCount:
        format: int32
        type: integer
      invalidOtpCount:
        format: int32
        type: integer
      lastInvalidDatetime:
        format: date-time
        type: string
      lastSuccessfulDateTime:
        format: date-time
        type: string
  ProblemDetails:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        format: int32
        type: integer
      detail:
        type: string
      instance:
        type: string
    additionalProperties:
      type: object
  JwtTokenPair:
    type: object
    properties:
      jwtAccessToken:
        type: string
      jwtRefreshToken:
        type: string
      token_type:
        type: string
        readOnly: true
  ConsumerTokenParameter:
    type: object
    properties:
      deviceId:
        type: string
      consumerId:
        type: string
      status:
        type: string
      impersonatedBy:
        type: string
      tenantId:
        type: string
  ConsumerMfaTokenParameter:
    type: object
    properties:
      deviceId:
        type: string
      consumerId:
        type: string
      tenantId:
        type: string
  DeviceTokenParameter:
    type: object
    properties:
      deviceId:
        type: string
      consumerId:
        type: string
      status:
        type: string
      marketId:
        format: int32
        type: integer
      tenantId:
        type: string
  MerchantTokenParameter:
    type: object
    properties:
      tenantId:
        type: string
  ConsumerActivityTokenParameter:
    type: object
    properties:
      gender:
        type: string
      dateOfBirth:
        format: date-time
        type: string
      deviceId:
        type: string
      consumerId:
        type: string
      status:
        type: string
      impersonatedBy:
        type: string
      tenantId:
        type: string
  'ValueTuple[String,String]':
    type: object
    properties:
      item1:
        type: string
      item2:
        type: string
  AuthorizationTenantConfiguration:
    type: object
    properties:
      consumerTokenExpiration:
        $ref: '#/definitions/TokenExpiration'
      merchantTokenExpiration:
        $ref: '#/definitions/TokenExpiration'
      activityTokenExpiration:
        $ref: '#/definitions/TokenExpiration'
      serviceTokenExpiration:
        $ref: '#/definitions/TokenExpiration'
      deviceTokenExpiration:
        $ref: '#/definitions/TokenExpiration'
  TokenExpiration:
    type: object
    properties:
      accessTokenExpiration:
        format: int64
        type: integer
      refreshTokenExpiration:
        format: int64
        type: integer
securityDefinitions:
  Bearer:
    name: Authorization
    in: header
    type: apiKey
    description: Please insert JWT with Bearer into field
security:
  - Bearer: []
